import type { CheckReport, MultiEngineCheckReport } from "./check";
import type { DoctorReport, SitemapReport } from "./types";
import {
  bold,
  bulletList,
  cyan,
  detectNarrow,
  dim,
  footer,
  glyphs,
  header,
  indent,
  kv,
  muted,
  rows,
  statusMark,
  type Row,
  type UiOptions,
} from "./ui";

/**
 * Renderers for `auto-geo doctor` and `auto-geo check`.
 *
 * Human renderers compose the building blocks from `cli/ui.ts`
 * (`header`, `rows`, `kv`, `divider`, `footer`, …) so all four
 * subcommands share the same visual language. JSON renderers are
 * unchanged — machine output stays stable across CLI versions so
 * downstream dashboards can rely on it.
 */

const REPO_URL = "github.com/shadowresearch/auto-geo";

// ── Single-page renderers (doctor) ────────────────────────────────

export function renderHumanReport(
  report: DoctorReport,
  opts: { colors: boolean; narrow?: boolean } = { colors: false }
): string {
  const ui = makeUi(opts);
  const lines: string[] = [];

  lines.push(header("auto-geo doctor", "GEO citation readiness audit", ui));
  lines.push("");
  lines.push(`${indent(ui)}${report.url}`);
  lines.push(
    `${indent(ui)}${dim(
      `${formatInt(report.wordCount)} word${report.wordCount === 1 ? "" : "s"}`,
      ui.colors
    )}`
  );
  lines.push("");

  // Aligned check rows — the centerpiece of the redesign.
  const rowItems: Row[] = report.checks.map((c) => ({
    status: c.pass ? "ok" : "fail",
    name: c.name,
    detail: c.detail,
  }));
  for (const row of rows(rowItems, ui)) lines.push(row);

  // Score callout — `▸ Score  N / T checks pass         posture`.
  lines.push("");
  lines.push(scoreLine(report, ui));

  // Top fixes block.
  if (report.topFixes.length > 0) {
    lines.push("");
    lines.push(
      `${indent(ui)}${bold(
        `Top ${report.topFixes.length === 1 ? "fix" : `${report.topFixes.length} fixes`} (citation lift):`,
        ui.colors
      )}`
    );
    const fixLines = bulletList(
      report.topFixes.map((f) => f.fixSuggestion),
      ui
    );
    for (const ln of fixLines) lines.push(ln);
  }

  // Footer with three short dim lines.
  const footerLines = footer(
    [
      `auto-geo doctor \u00b7 ${REPO_URL}`,
      `Audit another page: npx auto-geo doctor <url>`,
      `Learn more about GEO: shadow.inc/resources/what-is-geo`,
    ],
    ui
  );
  for (const ln of footerLines) lines.push(ln);

  // Legacy attribution line — preserved as a hidden marker so existing
  // tests / consumers grepping for "Generated by auto-geo doctor" keep
  // working. Dimmed so it doesn't compete with the new branded footer.
  lines.push(`${indent(ui)}${dim(`Generated by auto-geo doctor`, ui.colors)}`);

  return lines.join("\n");
}

export function renderJsonReport(report: DoctorReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Sitemap renderers ─────────────────────────────────────────────

export function renderSitemapHuman(
  report: SitemapReport,
  opts: { colors: boolean; topN?: number; narrow?: boolean } = {
    colors: false,
  }
): string {
  const ui = makeUi(opts);
  const topN = opts.topN ?? 5;
  const lines: string[] = [];

  lines.push(header("auto-geo doctor", "sitemap audit", ui));
  lines.push("");
  lines.push(kv("sitemap", report.sitemap, { ...ui, valueCol: 11 }));
  lines.push(
    kv("urls", `${report.total} URL${report.total === 1 ? "" : "s"}`, {
      ...ui,
      valueCol: 11,
    })
  );
  lines.push(
    kv(
      "mean",
      `${report.meanScorePct}% across ${report.pages.length} successfully fetched page${
        report.pages.length === 1 ? "" : "s"
      }`,
      { ...ui, valueCol: 11 }
    )
  );
  if (report.errors.length > 0) {
    lines.push(
      kv(
        "errors",
        `${report.errors.length} URL${report.errors.length === 1 ? "" : "s"} could not be fetched / parsed`,
        { ...ui, valueCol: 11, valueColor: "yellow" }
      )
    );
  }

  // Lowest-scoring pages — colored % column.
  if (report.pages.length > 0) {
    lines.push("");
    const sorted = [...report.pages].sort((a, b) => a.scorePct - b.scorePct);
    const worst = sorted.slice(0, topN);
    lines.push(
      `${indent(ui)}${bold(`Lowest-scoring pages (top ${worst.length}):`, ui.colors)}`
    );
    const worstRows: Row[] = worst.map((p) => ({
      status: p.scorePct >= 75 ? "ok" : p.scorePct >= 50 ? "warn" : "fail",
      name: `${p.scorePct}%`,
      detail: p.url,
    }));
    for (const ln of rows(worstRows, ui)) lines.push(ln);
  }

  if (report.failingChecks.length > 0) {
    lines.push("");
    lines.push(
      `${indent(ui)}${bold("Most common failing checks:", ui.colors)}`
    );
    for (const f of report.failingChecks) {
      lines.push(`${indent(ui)}  ${f.failureCount} pages: ${f.name}`);
    }
  }

  const footerLines = footer(
    [
      `auto-geo doctor (sitemap mode) \u00b7 ${REPO_URL}`,
      `Re-run on another sitemap: npx auto-geo doctor --site <url>`,
    ],
    ui
  );
  for (const ln of footerLines) lines.push(ln);
  lines.push(`${indent(ui)}${dim(`Generated by auto-geo doctor`, ui.colors)}`);

  return lines.join("\n");
}

export function renderSitemapJson(report: SitemapReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Check renderers ───────────────────────────────────────────────

/**
 * Renderer for `auto-geo check`. Same visual language as the doctor:
 * branded header, kv summary, aligned per-query rows, dim footer.
 *
 * Per-query rows surface the citation count + worst-case rank in the
 * detail column; uncited queries get a fail mark + a hostname preview.
 * Errored queries get a yellow warn mark.
 */
export function renderCheckHuman(
  report: CheckReport,
  opts: { colors: boolean; narrow?: boolean } = { colors: false }
): string {
  const ui = makeUi(opts);
  const g = glyphs(ui.colors);
  const lines: string[] = [];

  lines.push(
    header(
      "auto-geo check",
      "measure citation coverage in AI search engines",
      ui
    )
  );
  lines.push("");
  lines.push(kv("domain", report.domain, { ...ui, valueCol: 11 }));
  lines.push(
    kv("queries", String(report.summary.totalQueries), {
      ...ui,
      valueCol: 11,
    })
  );
  lines.push(
    kv("engine", `${report.engine} (${report.model})`, {
      ...ui,
      valueCol: 11,
    })
  );
  lines.push("");

  // Per-query rows. Each query gets a `[i/N] "query"` header, then a
  // single nested status row (cited / not cited / error) one level
  // deeper. We render the nested row inline rather than via `rows()` to
  // keep the alignment scoped to a single query.
  report.results.forEach((r, i) => {
    const idxLabel = dim(
      `[${i + 1}/${report.summary.totalQueries}]`,
      ui.colors
    );
    lines.push(`${indent(ui)}${idxLabel} ${JSON.stringify(r.query)}`);
    const nested = `${indent(ui)}  `;
    if (r.error) {
      lines.push(
        `${nested}${statusMark("warn", ui.colors)}  error  ${dim(r.error, ui.colors)}`
      );
      lines.push("");
      return;
    }
    if (r.cited) {
      const headline = `${report.domain} cited \u2014 ${r.citations.length} page${
        r.citations.length === 1 ? "" : "s"
      }`;
      lines.push(`${nested}${statusMark("ok", ui.colors)}  ${headline}`);
      for (const c of r.citations) {
        lines.push(
          `${nested}  ${dim(
            `${g.bullet} ${c.url} (rank ${c.rank} of ${c.totalCitationsForQuery})`,
            ui.colors
          )}`
        );
      }
    } else {
      const sources = r.rawSources;
      const preview = sources
        .slice(0, 2)
        .map((s) => safeHostname(s.url))
        .filter(Boolean)
        .join(", ");
      const tail =
        sources.length > 2 ? `${preview}, …` : preview || "no sources returned";
      const detail = `${sources.length} source${sources.length === 1 ? "" : "s"}${
        sources.length > 0 ? `: ${tail}` : ""
      }`;
      lines.push(
        `${nested}${statusMark("fail", ui.colors)}  ${report.domain} NOT cited  ${dim(`(${detail})`, ui.colors)}`
      );
    }
    lines.push("");
  });

  // Coverage callout (mirrors the doctor's score line).
  const { citedQueryCount, totalQueries, coveragePct, totalCitations } =
    report.summary;
  const costStr =
    report.summary.estimatedCostUsd > 0
      ? ` \u00b7 ~$${report.summary.estimatedCostUsd.toFixed(3)} spent`
      : "";
  lines.push(
    `${indent(ui)}${g.arrow} ${bold(
      `Coverage: ${citedQueryCount}/${totalQueries} queries (${coveragePct}%)`,
      ui.colors
    )}  ${dim(
      `${totalCitations} page citation${totalCitations === 1 ? "" : "s"} total${costStr}`,
      ui.colors
    )}`
  );

  if (report.summary.errors.length > 0) {
    lines.push(
      `${indent(ui)}${muted(
        `Errors: ${report.summary.errors.length} quer${
          report.summary.errors.length === 1 ? "y" : "ies"
        } failed (see report above)`,
        ui.colors
      )}`
    );
  }

  // Next steps block.
  lines.push("");
  lines.push(`${indent(ui)}${bold("Next steps:", ui.colors)}`);
  const steps = bulletList(
    [
      `Audit un-cited queries' targeted pages: npx auto-geo doctor <url>`,
      `Re-run \`auto-geo check\` after publishing new pages targeting uncited queries`,
    ],
    ui
  );
  for (const ln of steps) lines.push(ln);

  const footerLines = footer(
    [
      `auto-geo check \u00b7 ${REPO_URL}`,
      `Re-run: npx auto-geo check --domain ${report.domain} --query "<q>"`,
    ],
    ui
  );
  for (const ln of footerLines) lines.push(ln);
  lines.push(`${indent(ui)}${dim(`Generated by auto-geo check`, ui.colors)}`);

  return lines.join("\n");
}

export function renderCheckJson(report: CheckReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Multi-engine renderers ────────────────────────────────────────

/**
 * Human renderer for `--engine all`. Lays out a per-query roll-up
 * (✓/✗ per engine across columns) followed by the union + mean
 * coverage callouts, then the per-engine sub-summaries.
 */
export function renderMultiCheckHuman(
  report: MultiEngineCheckReport,
  opts: { colors: boolean; narrow?: boolean } = { colors: false }
): string {
  const ui = makeUi(opts);
  const g = glyphs(ui.colors);
  const lines: string[] = [];

  lines.push(
    header(
      "auto-geo check",
      "multi-engine citation coverage across the AI-search landscape",
      ui
    )
  );
  lines.push("");
  lines.push(kv("domain", report.domain, { ...ui, valueCol: 11 }));
  lines.push(
    kv("queries", String(report.summary.totalQueries), {
      ...ui,
      valueCol: 11,
    })
  );
  lines.push(
    kv(
      "engines",
      report.engines.length > 0
        ? report.engines.join(", ")
        : "(none — no API keys set)",
      { ...ui, valueCol: 11 }
    )
  );
  if (report.skippedEngines.length > 0) {
    lines.push(
      kv(
        "skipped",
        report.skippedEngines
          .map((s) => `${s.engine} (${s.reason})`)
          .join(", "),
        { ...ui, valueCol: 11, valueColor: "yellow" }
      )
    );
  }
  lines.push("");

  // Per-query roll-up — one row per query, with a compact engine
  // status string ("perplexity ✓, openai ✗, gemini ✓").
  report.acrossEngines.forEach((row, i) => {
    const idxLabel = dim(
      `[${i + 1}/${report.summary.totalQueries}]`,
      ui.colors
    );
    lines.push(`${indent(ui)}${idxLabel} ${JSON.stringify(row.query)}`);
    const nested = `${indent(ui)}  `;
    const mark = row.citedByAny
      ? statusMark("ok", ui.colors)
      : statusMark("fail", ui.colors);
    const headline = row.citedByAny
      ? `cited by ${row.citedByEngines.length}/${row.ranByEngines.length} engines`
      : `NOT cited by any of ${row.ranByEngines.length} engines`;
    lines.push(`${nested}${mark}  ${headline}`);
    const perEngineLine = row.ranByEngines
      .map((e) => `${e} ${row.citedByEngines.includes(e) ? g.ok : g.fail}`)
      .join("  ");
    if (perEngineLine) {
      lines.push(`${nested}  ${dim(perEngineLine, ui.colors)}`);
    }
    lines.push("");
  });

  // Union + mean coverage callouts.
  const {
    citedByAnyCount,
    totalQueries,
    unionCoveragePct,
    meanCoveragePct,
    estimatedCostUsd,
  } = report.summary;
  const costStr =
    estimatedCostUsd > 0
      ? ` \u00b7 ~$${estimatedCostUsd.toFixed(3)} spent total`
      : "";
  lines.push(
    `${indent(ui)}${g.arrow} ${bold(
      `Union coverage: ${citedByAnyCount}/${totalQueries} queries (${unionCoveragePct}%)`,
      ui.colors
    )}  ${dim(
      `cited by ≥1 engine\u00b7 mean per-engine coverage ${meanCoveragePct}%${costStr}`,
      ui.colors
    )}`
  );
  lines.push("");

  // Per-engine breakdown — one line per engine with its solo coverage.
  lines.push(`${indent(ui)}${bold("Per-engine breakdown:", ui.colors)}`);
  for (const engineId of report.engines) {
    const r = report.perEngine[engineId];
    if (!r) continue;
    const detail = `${r.summary.citedQueryCount}/${r.summary.totalQueries} queries (${r.summary.coveragePct}%)`;
    const status =
      r.summary.coveragePct >= 50
        ? "ok"
        : r.summary.coveragePct > 0
          ? "warn"
          : "fail";
    lines.push(
      `${indent(ui)}  ${statusMark(status, ui.colors)} ${engineId} (${r.model})  ${dim(detail, ui.colors)}`
    );
  }

  // Next steps.
  lines.push("");
  lines.push(`${indent(ui)}${bold("Next steps:", ui.colors)}`);
  const steps = bulletList(
    [
      `Audit pages targeting un-cited queries: npx auto-geo doctor <url>`,
      `Drill into one engine for full citation detail: npx auto-geo check --engine <name>`,
      `Re-run \`auto-geo check --engine all\` after publishing to track lift across engines`,
    ],
    ui
  );
  for (const ln of steps) lines.push(ln);

  const footerLines = footer(
    [
      `auto-geo check (multi-engine) \u00b7 ${REPO_URL}`,
      `Re-run: npx auto-geo check --engine all --domain ${report.domain} --query "<q>"`,
    ],
    ui
  );
  for (const ln of footerLines) lines.push(ln);
  lines.push(`${indent(ui)}${dim(`Generated by auto-geo check`, ui.colors)}`);

  return lines.join("\n");
}

export function renderMultiCheckJson(report: MultiEngineCheckReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Internals ─────────────────────────────────────────────────────

function makeUi(opts: { colors: boolean; narrow?: boolean }): UiOptions {
  const cols = process.stdout?.columns;
  return {
    colors: opts.colors,
    narrow: detectNarrow(cols, opts.narrow),
    width: cols,
  };
}

function scoreLine(report: DoctorReport, ui: UiOptions): string {
  const g = glyphs(ui.colors);
  const posture = scoreLabel(report.scorePct);
  // `Score:` (not `Score`) so downstream greps from v0.2.x keep working.
  const head = bold(
    `Score: ${report.score} / ${report.total} checks pass`,
    ui.colors
  );
  return `${indent(ui)}${g.arrow} ${head}  ${muted(`— ${posture} GEO posture`, ui.colors)}`;
}

function safeHostname(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

function scoreLabel(pct: number): string {
  if (pct >= 90) return "strong";
  if (pct >= 75) return "good";
  if (pct >= 50) return "moderate";
  if (pct >= 25) return "weak";
  return "poor";
}

function formatInt(n: number): string {
  return n.toLocaleString("en-US");
}

// Re-exports so callers can keep `import { cyan } from "./render"` etc.
// (the existing fix renderer relies on `cyan` to color the provider).
export { cyan };
