import type { CheckReport } from "./check";
import type { DoctorReport, SitemapReport } from "./types";

/**
 * Renderers for `auto-geo doctor` output.
 *
 * Two formats, two entry points each:
 *   - `renderHumanReport` / `renderSitemapHuman` — plain text for TTY.
 *     ANSI colors are applied if `colors: true`; otherwise plain ASCII
 *     so piping to file / CI logs stays clean.
 *   - `renderJsonReport` / `renderSitemapJson` — stable JSON serialization
 *     of the report shapes in `cli/types.ts`. Stable across CLI versions
 *     so downstream dashboards can rely on it.
 */

// ── ANSI helpers (avoid pulling in chalk to keep deps lean) ────────

const ANSI = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
};

function color(s: string, code: keyof typeof ANSI, on: boolean): string {
  return on ? `${ANSI[code]}${s}${ANSI.reset}` : s;
}

// ── Single-page renderers ─────────────────────────────────────────

export function renderHumanReport(
  report: DoctorReport,
  opts: { colors: boolean } = { colors: false }
): string {
  const { colors } = opts;
  const lines: string[] = [];

  lines.push(
    color("auto-geo doctor — GEO citation readiness audit", "bold", colors)
  );
  lines.push(
    `fetched ${report.url} (${formatInt(report.wordCount)} word${report.wordCount === 1 ? "" : "s"})`
  );
  lines.push("");

  for (const c of report.checks) {
    const mark = c.pass
      ? color("✓", "green", colors)
      : color("✗", "red", colors);
    lines.push(`${mark} ${c.name} (${c.detail})`);
  }

  lines.push("");
  const posture = scoreLabel(report.scorePct);
  lines.push(
    color(
      `Score: ${report.score} / ${report.total} checks pass — ${posture} GEO posture`,
      "bold",
      colors
    )
  );

  if (report.topFixes.length > 0) {
    lines.push("");
    lines.push(
      `Top ${report.topFixes.length} fixes (ranked by citation lift):`
    );
    report.topFixes.forEach((fix, i) => {
      lines.push(`  ${i + 1}. ${fix.fixSuggestion}`);
    });
  }

  lines.push("");
  lines.push(
    color(
      "Generated by auto-geo doctor (https://github.com/shadowresearch/auto-geo)",
      "dim",
      colors
    )
  );
  lines.push(
    color("Run on your other pages: npx auto-geo doctor <url>", "dim", colors)
  );
  lines.push(
    color(
      "Learn more about GEO: https://www.shadow.inc/resources/what-is-geo",
      "dim",
      colors
    )
  );

  return lines.join("\n");
}

export function renderJsonReport(report: DoctorReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Sitemap renderers ─────────────────────────────────────────────

export function renderSitemapHuman(
  report: SitemapReport,
  opts: { colors: boolean; topN?: number } = { colors: false }
): string {
  const { colors } = opts;
  const topN = opts.topN ?? 5;
  const lines: string[] = [];

  lines.push(color("auto-geo doctor — sitemap audit", "bold", colors));
  lines.push(
    `sitemap: ${report.sitemap} (${report.total} URL${report.total === 1 ? "" : "s"})`
  );
  lines.push(
    `mean score: ${report.meanScorePct}% across ${report.pages.length} successfully fetched page${report.pages.length === 1 ? "" : "s"}`
  );

  if (report.errors.length > 0) {
    lines.push(
      color(
        `errors: ${report.errors.length} URL${report.errors.length === 1 ? "" : "s"} could not be fetched / parsed`,
        "yellow",
        colors
      )
    );
  }
  lines.push("");

  // Top N pages by score (ascending — lowest first, because those need help).
  if (report.pages.length > 0) {
    const sorted = [...report.pages].sort((a, b) => a.scorePct - b.scorePct);
    const worst = sorted.slice(0, topN);
    lines.push(
      color(`Lowest-scoring pages (top ${worst.length}):`, "bold", colors)
    );
    for (const p of worst) {
      const m =
        p.scorePct >= 75 ? "green" : p.scorePct >= 50 ? "yellow" : "red";
      lines.push(`  ${color(`${p.scorePct}%`, m, colors)}  ${p.url}`);
    }
    lines.push("");
  }

  if (report.failingChecks.length > 0) {
    lines.push(color("Most common failing checks:", "bold", colors));
    for (const f of report.failingChecks) {
      lines.push(`  ${f.failureCount} pages: ${f.name}`);
    }
    lines.push("");
  }

  lines.push(
    color(
      "Generated by auto-geo doctor (https://github.com/shadowresearch/auto-geo)",
      "dim",
      colors
    )
  );

  return lines.join("\n");
}

export function renderSitemapJson(report: SitemapReport): string {
  return JSON.stringify(report, null, 2);
}

// ── Check renderers ───────────────────────────────────────────────

/**
 * Renderer for `auto-geo check` reports. Mirrors the doctor renderers'
 * conventions: ANSI helpers, plain ASCII by default, stable JSON sister
 * function for `--json`. Layout matches the spec in `docs/check.md`:
 *
 *   header → per-query bullets → coverage line → next-steps block
 */
export function renderCheckHuman(
  report: CheckReport,
  opts: { colors: boolean } = { colors: false }
): string {
  const { colors } = opts;
  const lines: string[] = [];

  lines.push(
    color(
      "auto-geo check — measure citation coverage in AI search engines",
      "bold",
      colors
    )
  );
  lines.push(`domain:    ${report.domain}`);
  lines.push(`queries:   ${report.summary.totalQueries}`);
  lines.push(`engine:    ${report.engine} (${report.model})`);
  lines.push("");

  report.results.forEach((r, i) => {
    const idx = `[${i + 1}/${report.summary.totalQueries}]`;
    lines.push(`${idx} "${r.query}"`);
    if (r.error) {
      lines.push(`  ${color("!", "yellow", colors)} error — ${r.error}`);
      lines.push("");
      return;
    }
    if (r.cited) {
      const head = color(
        `✓ ${report.domain} cited — ${r.citations.length} page${r.citations.length === 1 ? "" : "s"}`,
        "green",
        colors
      );
      lines.push(`  ${head}`);
      for (const c of r.citations) {
        lines.push(
          `    · ${c.url} (rank ${c.rank} of ${c.totalCitationsForQuery})`
        );
      }
    } else {
      const sources = r.rawSources;
      const preview = sources
        .slice(0, 2)
        .map((s) => safeHostname(s.url))
        .filter(Boolean)
        .join(", ");
      const tail =
        sources.length > 2 ? `${preview}, …` : preview || "no sources returned";
      const head = color(
        `✗ ${report.domain} NOT cited (${sources.length} source${sources.length === 1 ? "" : "s"}${sources.length > 0 ? `: ${tail}` : ""})`,
        "red",
        colors
      );
      lines.push(`  ${head}`);
    }
    lines.push("");
  });

  const { citedQueryCount, totalQueries, coveragePct, totalCitations } =
    report.summary;
  const costStr =
    report.summary.estimatedCostUsd > 0
      ? ` · ~$${report.summary.estimatedCostUsd.toFixed(3)} spent`
      : "";
  lines.push(
    color(
      `Coverage: ${citedQueryCount}/${totalQueries} queries (${coveragePct}%) · ${totalCitations} page citation${totalCitations === 1 ? "" : "s"} total${costStr}`,
      "bold",
      colors
    )
  );

  if (report.summary.errors.length > 0) {
    lines.push(
      color(
        `Errors: ${report.summary.errors.length} quer${report.summary.errors.length === 1 ? "y" : "ies"} failed (see report above)`,
        "yellow",
        colors
      )
    );
  }

  lines.push("");
  lines.push("Next steps:");
  lines.push(
    `  - Audit the un-cited queries' targeted pages with \`npx auto-geo doctor <url>\``
  );
  lines.push(
    `  - Re-run \`auto-geo check\` after publishing new pages targeting uncited queries`
  );
  lines.push("");
  lines.push(
    color(
      "Generated by auto-geo check (https://github.com/shadowresearch/auto-geo)",
      "dim",
      colors
    )
  );

  return lines.join("\n");
}

export function renderCheckJson(report: CheckReport): string {
  return JSON.stringify(report, null, 2);
}

function safeHostname(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

// ── Internals ─────────────────────────────────────────────────────

function scoreLabel(pct: number): string {
  if (pct >= 90) return "strong";
  if (pct >= 75) return "good";
  if (pct >= 50) return "moderate";
  if (pct >= 25) return "weak";
  return "poor";
}

function formatInt(n: number): string {
  return n.toLocaleString("en-US");
}
