/**
 * Shared types for `auto-geo doctor`. Kept in their own module so the
 * pure-heuristic layer (`cli/checks.ts`), the parser layer (`cli/fetch.ts`),
 * and the renderers (`cli/render.ts`) all reference the same shapes — and
 * downstream consumers wiring `--json` into their own dashboards have a
 * single source of truth to import from.
 */

/** Stable identifier for a single GEO check. Used in JSON output as a key. */
export type CheckId =
  | "tldr-present"
  | "question-h2"
  | "article-jsonld"
  | "faqpage-jsonld"
  | "entity-density"
  | "image-cadence"
  | "answer-first"
  | "no-self-link";

/**
 * Result of one heuristic against one page.
 *
 * `citationImpactRank` is the SOP-derived "fix this first" ordering used
 * to power the "Top 3 fixes" section of the human-readable report. Lower
 * == higher impact. We assign these statically (per check) rather than
 * dynamically because the SOP's empirical guidance is itself static.
 */
export type CheckResult = {
  id: CheckId;
  /** Human-readable name. Shown in the bullet line. */
  name: string;
  pass: boolean;
  /** Short factual detail — what was found, in numbers when possible. */
  detail: string;
  /** Imperative one-liner the user can act on if `pass` is false. */
  fixSuggestion: string;
  /**
   * 1 = fix this first. Used to rank the "Top 3 fixes" section.
   * Mirrors the SOP's empirical guidance on which signals carry the
   * largest measured citation lift.
   */
  citationImpactRank: number;
  /** Optional SOP section reference for traceability. */
  sop?: string;
};

/**
 * Normalized snapshot of a fetched page, produced by `cli/fetch.ts` and
 * consumed by `cli/checks.ts`. Keeping checks pure functions over this
 * shape means every heuristic is unit-testable from a hand-built object
 * without touching `fetch` or `linkedom`.
 */
export type ParsedPage = {
  url: string;
  /** Full document text content, with nav/footer stripped where identifiable. */
  text: string;
  /** Word count of `text`. */
  wordCount: number;
  /** Top-block text before any H2 — the candidate TL;DR region. */
  leadText: string;
  /** First paragraph text (used for answer-first heuristic). */
  firstParagraph: string;
  /** All H1/H2/H3 text content, in document order. */
  headings: Array<{ level: 1 | 2 | 3; text: string }>;
  /** Parsed JSON-LD blocks (already JSON.parsed; unparseable blocks dropped). */
  jsonLd: unknown[];
  /** Image alt attributes (count + content). Empty string for missing alt. */
  images: Array<{ alt: string; src: string }>;
  /** Anchor hrefs, normalized (kept raw if non-URL). */
  links: Array<{ href: string; text: string; inRelatedSection: boolean }>;
};

export type DoctorReport = {
  url: string;
  wordCount: number;
  /** Number of passing checks. */
  score: number;
  /** Total number of checks run. */
  total: number;
  /** score / total expressed as a percentage 0-100, rounded. */
  scorePct: number;
  /** All check results, ordered as run. */
  checks: CheckResult[];
  /** Top fixes, ranked by citationImpactRank. Empty if all checks pass. */
  topFixes: CheckResult[];
  /**
   * Generated by version — recorded so downstream dashboards can detect
   * threshold changes between auto-geo releases when comparing snapshots.
   */
  generatedBy: string;
};

export type SitemapReport = {
  sitemap: string;
  /** Total URLs discovered in the sitemap. */
  total: number;
  /** Per-URL reports, in the order processed. */
  pages: DoctorReport[];
  /** Mean score across all successfully-fetched pages, 0-100. */
  meanScorePct: number;
  /**
   * Aggregated by check id — how often each check fails across the corpus.
   * Sorted descending by failure count.
   */
  failingChecks: Array<{ id: CheckId; name: string; failureCount: number }>;
  /** URLs that failed to fetch / parse, with the error string. */
  errors: Array<{ url: string; error: string }>;
};
